/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instalador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.io.File;
import javax.swing.JFileChooser;

/**
 * This class represents the program installation frame 2, in it we can find
 * a next button, a previous button, a text with the conditions that must be accepted
 * and a checkbox to accept said conditions.
 * @author Admin
 */
public class pantalla_2 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form pantalla_2
     */
    pantalla_1 pant_1; //frame previus
    pantalla_3 pant_3; //next frame
    public pantalla_2() {
        initComponents();
        
        next.setVisible(false);
        
        btnRuta.setEnabled(false);
        buscarRuta.setEditable(false);
        
        /**
         * Action Listener from buttons and chekbox
         */
        deAcuerdo.addActionListener(this);
        previus.addActionListener(this);
        next.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        deAcuerdo = new javax.swing.JRadioButton();
        next = new javax.swing.JButton();
        previus = new javax.swing.JButton();
        buscarRuta = new javax.swing.JTextField();
        btnRuta = new javax.swing.JButton();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setText("REQUISITOS Y NORMAS:");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 0, 361, 81));

        jTextArea1.setEditable(false);
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        jTextArea1.setRows(5);
        jTextArea1.setText("-Los requisitos para usar del programa son:\n--> Grafica: RTX 4090 ti\n--> CPU: RYZEN 9 5950x\n--> RAM: 32GB \n--> Disco: 100GB\n\n-Nuestros terminos y condiciones se basan \n en la norma actual europea y americana\n de uso de datos por lo que si acepta usted\n se compromete a:\n\n--> Ceder sus datos a cualquier uso que se les \npueda dar.\n--> A pagar 10 dolares o 7 euros mensuales.\n--> Nunca desistalar la aplicación.\n\n-Si esta de acuerdo acepte para continuar \n la instalación");
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 70, 330, 110));

        deAcuerdo.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        deAcuerdo.setText("I agree");
        getContentPane().add(deAcuerdo, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 200, -1, -1));

        next.setBackground(new java.awt.Color(204, 204, 204));
        next.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        next.setText("NEXT");
        next.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nextActionPerformed(evt);
            }
        });
        getContentPane().add(next, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, -1, -1));

        previus.setBackground(new java.awt.Color(204, 204, 204));
        previus.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        previus.setText("PREVIUS");
        getContentPane().add(previus, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, -1, -1));

        buscarRuta.setText("/root/Escritorio");
        getContentPane().add(buscarRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 240, 240, -1));

        btnRuta.setText("...");
        btnRuta.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRutaActionPerformed(evt);
            }
        });
        getContentPane().add(btnRuta, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 240, -1, -1));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 10, 420, 330));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nextActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nextActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nextActionPerformed

    /**
     * The code in this button allows us to choose an installation path
     * @param evt 
     */
    private void btnRutaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRutaActionPerformed
        JFileChooser file = new JFileChooser();
        file.setCurrentDirectory(new File("."));
        file.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        file.setSize(380, 100);
        int result = file.showOpenDialog(this);
        
        if(result != JFileChooser.CANCEL_OPTION){
            File nombreArchivo = file.getSelectedFile();
            
            if((nombreArchivo==null) || (nombreArchivo.getName().equals(""))){
                buscarRuta.setText("...");
            }else{
                buscarRuta.setText(nombreArchivo.getAbsolutePath());
            }
        }
    }//GEN-LAST:event_btnRutaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_2.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_2().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnRuta;
    private javax.swing.JTextField buscarRuta;
    private javax.swing.JRadioButton deAcuerdo;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    private javax.swing.JButton next;
    private javax.swing.JButton previus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(deAcuerdo.isSelected()){ //If checkbox is selected, button next is visible
            next.setVisible(true);
            btnRuta.setEnabled(true);
            buscarRuta.setEnabled(true);
        } else {
            next.setVisible(false);
        }
        
        if(e.getSource()==previus){ //If previus is selected, the form 1 is visible and this frame goes invisible.
            pant_1= new pantalla_1();
            this.setVisible(false);
            pant_1.setVisible(true);
        }else if(e.getSource()==next){
            pant_3= new pantalla_3();
            this.setVisible(false);
            pant_3.setVisible(true);
        }
    }
}
