/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instalador;

import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import javax.swing.ImageIcon;


/**
 * This Jframe basically has a button that leads to another jframe and an image of the hotel logo.
 * Herdade actionlistener that allows us to give functionality to objects
 * @author Admin
 */
public class pantalla_1 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form pantalla_1
     */
    pantalla_2 pan_2; //This is a second form
    public pantalla_1() {
        initComponents();
         /*
        This is a picture of the hotel 
        */
        ImageIcon hotelImagen = new ImageIcon("src/instal_hotel.png");
        instalHotel.setIcon(hotelImagen);
        
        siguiente.addActionListener(this); //This action take us a second frame
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        instalHotel = new javax.swing.JLabel();
        siguiente = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(102, 102, 102));
        setPreferredSize(new java.awt.Dimension(500, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        jLabel1.setText("INSTALADOR DE HOTEL INSTANT");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 0, 396, 87));
        getContentPane().add(instalHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 80, 230, 190));

        siguiente.setBackground(new java.awt.Color(204, 204, 204));
        siguiente.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        siguiente.setText("NEXT");
        getContentPane().add(siguiente, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 310, 120, 40));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_1.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_1().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel instalHotel;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton siguiente;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==siguiente){
            pan_2 = new pantalla_2(); //Declaration of a second frame
            pan_2.setVisible(true); //Visivility true in second frame
            this.setVisible(false);//Visivility false in this frame
        }
    }
}
