/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package instalador;

import java.awt.GridLayout;
import java.awt.Rectangle;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.JPanel;
import javax.swing.JProgressBar;

/**
 * This is the final installation frame of the program and it has a button to 
 * install the program on the computer.
 *When the program is being installed, a progress bar is displayed.
 *This frame has a button to return to frame 2.
 *It also has a message to notify the user that the program has been installed.
 * @author Admin
 */
public class pantalla_3 extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form pantalla_3
     */
    
    pantalla_2 pant_2; //is a frame 2
    public pantalla_3() {
        initComponents();
        /**
         * At the first time in execution, the items have this state.
         */
        bar.setVisible(false);
        instalLabel.setVisible(false);
        
        instalar.addActionListener(this); //Is a action listener of install button.
        previus.addActionListener(this); //Is a action listener of a previus frame button.
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBoxMenuItem1 = new javax.swing.JCheckBoxMenuItem();
        label1 = new javax.swing.JLabel();
        instalar = new javax.swing.JButton();
        bar = new javax.swing.JProgressBar();
        instalLabel = new javax.swing.JLabel();
        previus = new javax.swing.JButton();

        jCheckBoxMenuItem1.setSelected(true);
        jCheckBoxMenuItem1.setText("jCheckBoxMenuItem1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(350, 100));
        setPreferredSize(new java.awt.Dimension(380, 290));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        label1.setFont(new java.awt.Font("Serif", 1, 36)); // NOI18N
        label1.setText("INSTALACIÓN:");
        getContentPane().add(label1, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 20, 280, -1));

        instalar.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        instalar.setText("INSTALAR");
        getContentPane().add(instalar, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 90, -1, -1));
        getContentPane().add(bar, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 140, 290, 20));

        instalLabel.setFont(new java.awt.Font("Segoe UI Symbol", 1, 16)); // NOI18N
        instalLabel.setForeground(new java.awt.Color(255, 102, 0));
        instalLabel.setText("Instalando...");
        getContentPane().add(instalLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 160, -1, -1));

        previus.setFont(new java.awt.Font("Serif", 1, 14)); // NOI18N
        previus.setText("PREVIUS");
        getContentPane().add(previus, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 200, -1, -1));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(pantalla_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(pantalla_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(pantalla_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(pantalla_3.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new pantalla_3().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JProgressBar bar;
    private javax.swing.JLabel instalLabel;
    private javax.swing.JButton instalar;
    private javax.swing.JCheckBoxMenuItem jCheckBoxMenuItem1;
    private javax.swing.JLabel label1;
    private javax.swing.JButton previus;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==instalar){
            try {
                instalLabel.setVisible(true);
                Thread.sleep(100);
                barraProgreso();
                instalLabel.setText("Programa instalado.");
                
                JOptionPane.showMessageDialog(this, "El programa se ha instalado correctamente.");
                System.exit(0);
            } catch (InterruptedException ex) {
                Logger.getLogger(pantalla_3.class.getName()).log(Level.SEVERE, null, ex);
            }
        }else if(e.getSource()== previus){
            pant_2= new pantalla_2();
            this.setVisible(false);
            pant_2.setVisible(true);
        }
    }
    
    
    
    /**
     * This method simulated a progress bar in the program.
     * Use the loop for and methods with progress bar.
     * @throws InterruptedException 
     */
    public void barraProgreso() throws InterruptedException{
        bar.setVisible(true);
        for(int i =1; i<=100;i++){
            bar.setValue(i);
            Thread.sleep(100);
            Rectangle progreso = bar.getBounds();
            progreso.x=0;
            progreso.y=0;
            bar.paintImmediately(progreso);
        }
        
        
    }
}
