/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import bd.AccesoBD;
import bd.ManejadorDB;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;

/**
 * In this frame you can modify a reservation.
 * The reservation will be searched by its id in the database.
 * The search button only appears if the reservation is in the database.
 * @author Admin
 */
public class Modificar_Reserva extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Modificar_Reserva
     */
    Pantalla_Principal framePrin; //is a firt frame of program
    public Modificar_Reserva() {
        initComponents();
        ImageIcon fondo1 = new ImageIcon("src/fondoAPP.png");
        fondo2.setIcon(fondo1);
        modificar.setVisible(false);
        
        
        ImageIcon vol = new ImageIcon("src/volver.png");
        volver.setIcon(vol);
        volver.setBorder(BorderFactory.createEmptyBorder());
        volver.setBackground(new Color(0,0,0,0));
        volver.addActionListener(this);
    }

    
    /**
     * This methond check if DNI is ok.
     * @param dni is a dni
     * @return boolena 
     */
    public boolean compDni(String dni) {
        try {
            Integer.parseInt(dni.substring(0, 8));
            char letra = dni.charAt(8);

            if (letra < 65 || letra > 90) {
                return false;

            } else {
                return true;
            }
        } catch (Exception e) {
            System.err.println(e);
            return false;
        }
    }

    
    /**
     * This methond check if id of reservation is a int.
     * @param num is a id of reservation
     * @return boolena 
     */
    public boolean compNum(String num) {
        try {
            int x = Integer.parseInt(num);
            return true;
        } catch (Exception e) {
            return false;
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        fondo = new javax.swing.JLabel();
        txtModificarReserva = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        nombreF = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        dniL = new javax.swing.JLabel();
        dniF = new javax.swing.JTextField();
        jSeparator3 = new javax.swing.JSeparator();
        conocidoL = new javax.swing.JLabel();
        conocidoF = new javax.swing.JComboBox<>();
        claseL = new javax.swing.JLabel();
        alta = new javax.swing.JRadioButton();
        baja = new javax.swing.JRadioButton();
        modificar = new javax.swing.JButton();
        jSeparator4 = new javax.swing.JSeparator();
        idL = new javax.swing.JLabel();
        idBuscar = new javax.swing.JTextField();
        buscarID = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtModificarReserva.setFont(new java.awt.Font("Times New Roman", 1, 26)); // NOI18N
        txtModificarReserva.setForeground(new java.awt.Color(51, 51, 51));
        txtModificarReserva.setText("MODIFICAR RESERVA");
        getContentPane().add(txtModificarReserva, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 380, -1));

        nombreL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nombreL.setForeground(new java.awt.Color(51, 51, 51));
        nombreL.setText("Introduce tu nombre:");
        getContentPane().add(nombreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 80, -1, -1));

        nombreF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFActionPerformed(evt);
            }
        });
        getContentPane().add(nombreF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 110, 120, -1));

        jSeparator2.setBackground(new java.awt.Color(153, 153, 153));
        jSeparator2.setForeground(new java.awt.Color(153, 153, 153));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 370, 10));

        dniL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dniL.setForeground(new java.awt.Color(51, 51, 51));
        dniL.setText("Introduce tu DNI:");
        getContentPane().add(dniL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 150, -1, -1));
        getContentPane().add(dniF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 180, 120, -1));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 210, 370, 10));

        conocidoL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        conocidoL.setForeground(new java.awt.Color(51, 51, 51));
        conocidoL.setText("Indica como nos has conocido:");
        getContentPane().add(conocidoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 220, -1, -1));

        conocidoF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por internet", "Recomendacion", "Por busqueda propia" }));
        getContentPane().add(conocidoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 250, -1, -1));

        claseL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        claseL.setForeground(new java.awt.Color(51, 51, 51));
        claseL.setText("Introduce la clase:");
        getContentPane().add(claseL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 290, -1, -1));

        buttonGroup1.add(alta);
        alta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alta.setText("ALTA");
        getContentPane().add(alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 320, -1, -1));

        buttonGroup1.add(baja);
        baja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        baja.setSelected(true);
        baja.setText("BAJA");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });
        getContentPane().add(baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 320, -1, -1));

        modificar.setBackground(new java.awt.Color(0, 0, 0));
        modificar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        modificar.setForeground(new java.awt.Color(255, 255, 255));
        modificar.setText("MODIFICAR");
        modificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                modificarActionPerformed(evt);
            }
        });
        getContentPane().add(modificar, new org.netbeans.lib.awtextra.AbsoluteConstraints(170, 360, 150, 40));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 280, 370, 10));

        idL.setFont(new java.awt.Font("Segoe UI", 3, 14)); // NOI18N
        idL.setText("ID reserva:");
        getContentPane().add(idL, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 40, -1, -1));
        getContentPane().add(idBuscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 40, 30, -1));

        buscarID.setText("BUSCAR");
        buscarID.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarIDActionPerformed(evt);
            }
        });
        getContentPane().add(buscarID, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 40, -1, -1));

        volver.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                volverActionPerformed(evt);
            }
        });
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        getContentPane().add(fondo2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 500, 430));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaActionPerformed

    /**
     * If you press the modify button, the data is modified.
     * Pressing this button will access the database and update the 
     * reservation data.
     * When modifying the reservation, the fields on the screen will be cleared.
     * @param evt 
     */
    private void modificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_modificarActionPerformed
        try {

            if (compDni(dniF.getText())) {
                AccesoBD acceso = new AccesoBD("hotel_interfaces");
                if (alta.isSelected()) {
                    acceso.modificarReserva(Integer.parseInt(idBuscar.getText().toString()), nombreF.getText(), dniF.getText(), conocidoF.getSelectedItem().toString(), alta.getText());
                    JOptionPane.showMessageDialog(this, "Persona actualizada con exito.");
                    idBuscar.setText("");
                    nombreF.setText("");
                    dniF.setText("");
                    
                } else {
                    acceso.modificarReserva(Integer.parseInt(idBuscar.getText().toString()), nombreF.getText(), dniF.getText(), conocidoF.getSelectedItem().toString(), baja.getText());
                    JOptionPane.showMessageDialog(this, "Persona actualizada con exito.");
                    idBuscar.setText("");
                    nombreF.setText("");
                    dniF.setText("");
                }
            } else {
                idBuscar.setText("");
                nombreF.setText("");
                dniF.setText("");
                JOptionPane.showMessageDialog(this, "Los datos no son correctos", "Error", JOptionPane.ERROR_MESSAGE);
            }
        } catch (SQLException ex) {
            Logger.getLogger(Modificar_Reserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_modificarActionPerformed

    private void buscarIDActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarIDActionPerformed
        try {
            /**
             * If you press this button, search the database for the reservation
             * with that id and the fields on the screen will be filled in with 
             * the fields obtained in the database so that the user knows what 
             * to modify.
             * If the id is not a number or is not found in the database, 
             * a warning message will be issued.
             */
            if (compNum(idBuscar.getText())) {
                ManejadorDB db = new ManejadorDB("hotel_interfaces");
                ResultSet rr = db.consulta("SELECT * FROM reservas WHERE id = " + idBuscar.getText());
                while (rr.next()) {
                    nombreF.setText(rr.getString("nombre"));
                    dniF.setText(rr.getString("dni"));
                    conocidoF.setSelectedItem(rr.getString("encontrado"));
                    if (rr.getString("clase") == "BAJA") {
                        alta.setSelected(false);
                        baja.setSelected(true);
                    } else if (rr.getString("clase") == "ALTA") {
                        alta.setSelected(true);
                        baja.setSelected(false);
                    }

                    
                    
                    
                    if(rr.isAfterLast()){
                        modificar.setVisible(false);
                        JOptionPane.showMessageDialog(this, "El id no se encuentra en la base de datos. Comprueba que se encuentre en la opcion 'Ver reservas'.");
                    }else{
                        modificar.setVisible(true);
                    }
                }
                db.cerrar();
                rr.close();
            }else{
                JOptionPane.showMessageDialog(this, "Introduce un numero entero.", "Error", JOptionPane.ERROR_MESSAGE);

            }

        } catch (SQLException ex) {
            Logger.getLogger(Modificar_Reserva.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_buscarIDActionPerformed

    private void volverActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_volverActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_volverActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Modificar_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Modificar_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Modificar_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Modificar_Reserva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Modificar_Reserva().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alta;
    private javax.swing.JRadioButton baja;
    private javax.swing.JButton buscarID;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel claseL;
    private javax.swing.JComboBox<String> conocidoF;
    private javax.swing.JLabel conocidoL;
    private javax.swing.JTextField dniF;
    private javax.swing.JLabel dniL;
    private javax.swing.JLabel fondo;
    private javax.swing.JLabel fondo2;
    private javax.swing.JTextField idBuscar;
    private javax.swing.JLabel idL;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JButton modificar;
    private javax.swing.JTextField nombreF;
    private javax.swing.JLabel nombreL;
    private javax.swing.JLabel txtModificarReserva;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        if(e.getSource()==volver){
            try {
                framePrin = new Pantalla_Principal();
                framePrin.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Reservar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }

    }
}
