/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import bd.ManejadorDB;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JTextField;

/**
 * In this frame you can view in more detail the information about the hotel 
 * you want to book.
 * It has the description, the price, the location and the button to go to the
 * reserve frame.
 * @author Admin
 */
public class Pantalla_Descriptiva extends javax.swing.JFrame implements ActionListener {

    /**
     * Creates new form Pantalla_Reservas
     */
    Reservar frameReserva = new Reservar(); //Is a reserve frame.
    JTextField idHotel; //is a hotel id.
    public Pantalla_Descriptiva() throws SQLException {
        initComponents();
        idHotel = new JTextField();
        
        
        /**
         * Change the backgound for JTextArea and button
         */
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        jScrollPane1.setBorder(null);
        jScrollPane1.setViewportBorder(null);
        
        descripcion.setBackground(new Color(0,0,0,5));
        descripcion.setBorder(null);
        descripcion.setLineWrap(true);
        
        reservar.setOpaque(false);
        reservar.setBackground(new Color(0,0,0,6));
        reservar.setBorder(null);
        
        ImageIcon fondo = new ImageIcon("src/fondoAPP.png");
        fondoAPP.setIcon(fondo);
        
        ImageIcon vol = new ImageIcon("src/volver.png");
        volver.setIcon(vol);
        volver.setBorder(BorderFactory.createEmptyBorder());
        volver.setBackground(new Color(0,0,0,0));
        
       ImageIcon ubi = new ImageIcon("src/ubicacion.png");
        ubicacion2.setIcon(ubi);
        
        /**
         * Action listener for a buttons
         */
        volver.addActionListener(this);
        reservar.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        ubicacion1 = new javax.swing.JLabel();
        titulo = new javax.swing.JLabel();
        precio = new javax.swing.JLabel();
        reservar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        ubicacion = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        descripcion = new javax.swing.JTextArea();
        imagenHotel = new javax.swing.JLabel();
        ubicacion2 = new javax.swing.JLabel();
        fondoAPP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(600, 400));
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        titulo.setFont(new java.awt.Font("Segoe UI", 3, 48)); // NOI18N
        titulo.setText("jLabel1");
        getContentPane().add(titulo, new org.netbeans.lib.awtextra.AbsoluteConstraints(220, 20, 430, -1));

        precio.setFont(new java.awt.Font("Yu Gothic UI", 1, 24)); // NOI18N
        precio.setForeground(new java.awt.Color(0, 102, 0));
        precio.setText("jLabel2");
        getContentPane().add(precio, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 290, 140, 44));

        reservar.setBackground(new java.awt.Color(204, 153, 255));
        reservar.setFont(new java.awt.Font("Segoe UI", 3, 18)); // NOI18N
        reservar.setForeground(new java.awt.Color(255, 255, 255));
        reservar.setText("RESERVAR");
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });
        getContentPane().add(reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 310, 130, -1));
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));

        ubicacion.setFont(new java.awt.Font("Segoe UI", 1, 19)); // NOI18N
        ubicacion.setText("jLabel1");
        getContentPane().add(ubicacion, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, 160, -1));

        descripcion.setEditable(false);
        descripcion.setColumns(20);
        descripcion.setFont(new java.awt.Font("Times New Roman", 0, 15)); // NOI18N
        descripcion.setRows(5);
        jScrollPane1.setViewportView(descripcion);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 110, 350, 160));
        getContentPane().add(imagenHotel, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 170, 140));
        getContentPane().add(ubicacion2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 260, 40, 40));
        getContentPane().add(fondoAPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 690, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                try {
                    new Pantalla_Descriptiva().setVisible(true);
                } catch (SQLException ex) {
                    Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(Level.SEVERE, null, ex);
                }
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    public static javax.swing.JTextArea descripcion;
    private javax.swing.JLabel fondoAPP;
    public static javax.swing.JLabel imagenHotel;
    private javax.swing.JScrollPane jScrollPane1;
    public static javax.swing.JLabel precio;
    private javax.swing.JButton reservar;
    public static javax.swing.JLabel titulo;
    public static javax.swing.JLabel ubicacion;
    private javax.swing.JLabel ubicacion1;
    private javax.swing.JLabel ubicacion2;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        /**
         * If you press this button you can go back to the previous frame.
         */
        if(e.getSource()==volver){
            Pantalla_Principal p = null;
            try {
                p = new Pantalla_Principal();
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            p.setVisible(true);
            
         /**
          * If you press this button you can access the reservation frame 
          * to reserve a room.
          * Pressing this button also sends the id of the reservation so that
          * it is saved in the user's reservation.
          */   
        }else if (e.getSource()==reservar){
            frameReserva.setVisible(true);
            this.setVisible(false);
            frameReserva.idHotel.setText(idHotel.getText().toString());
        }
    }
}
