/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import bd.AccesoBD;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.JTextField;

/**
 * 
 *In this jframe you can book a room in the hotel.
 *It has different elements such as radioButton, TextField, comboBox...
 * @author Admin
 */
public class Reservar extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Reservar
     */
    Pantalla_Principal framePrin; //This is a first program frame
    AccesoBD bd; //With this class we access the database.
    JTextField idHotel;
    public Reservar() {
        initComponents();
        
       
        
        ImageIcon fondo1 = new ImageIcon("src/fondoAPP.png");
        fondoAPP.setIcon(fondo1);
        
        
        /**
         * Change background for vuttons and icons
         */
        reservar.setOpaque(false);
        reservar.setBackground(new Color(0,0,0,6));
        reservar.setBorder(null);
        
        ImageIcon vol = new ImageIcon("src/volver.png");
        volver.setIcon(vol);
        volver.setBorder(BorderFactory.createEmptyBorder());
        volver.setBackground(new Color(0,0,0,0));
        volver.addActionListener(this);
        
        idHotel = new JTextField();
        
        
        
        reservar.addActionListener(this); //Action Listner for button reservar
    }
    
    
    /**
     * This methond check if DNI is ok.
     * @param dni is a dni
     * @return boolena 
     */
    public boolean compDni(String dni) {
        try {
            Integer.parseInt(dni.substring(0, 8));
            char letra = dni.charAt(8);

            if (letra < 65 || letra > 90) {
                return false;

            } else {
                return true;
            }
        } catch (Exception e) {
            System.err.println(e);
            return false;
        }
    }
    
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        txtReservarHab = new javax.swing.JLabel();
        dniL = new javax.swing.JLabel();
        conocidoL = new javax.swing.JLabel();
        nombreL = new javax.swing.JLabel();
        claseL = new javax.swing.JLabel();
        dniF = new javax.swing.JTextField();
        nombreF = new javax.swing.JTextField();
        conocidoF = new javax.swing.JComboBox<>();
        alta = new javax.swing.JRadioButton();
        baja = new javax.swing.JRadioButton();
        reservar = new javax.swing.JButton();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jSeparator4 = new javax.swing.JSeparator();
        volver = new javax.swing.JButton();
        fondoAPP = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        txtReservarHab.setFont(new java.awt.Font("Times New Roman", 1, 30)); // NOI18N
        txtReservarHab.setForeground(new java.awt.Color(51, 51, 51));
        txtReservarHab.setText("RESERVAR HABITACIÓN");
        getContentPane().add(txtReservarHab, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 0, 450, -1));

        dniL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        dniL.setForeground(new java.awt.Color(51, 51, 51));
        dniL.setText("Introduce tu DNI:");
        getContentPane().add(dniL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 120, -1, -1));

        conocidoL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        conocidoL.setForeground(new java.awt.Color(51, 51, 51));
        conocidoL.setText("Indica como nos has conocido:");
        getContentPane().add(conocidoL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 190, -1, -1));

        nombreL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        nombreL.setForeground(new java.awt.Color(51, 51, 51));
        nombreL.setText("Introduce tu nombre:");
        getContentPane().add(nombreL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        claseL.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        claseL.setForeground(new java.awt.Color(51, 51, 51));
        claseL.setText("Introduce la clase:");
        getContentPane().add(claseL, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 260, -1, -1));
        getContentPane().add(dniF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 150, 120, -1));

        nombreF.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                nombreFActionPerformed(evt);
            }
        });
        getContentPane().add(nombreF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 80, 120, -1));

        conocidoF.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Por internet", "Recomendacion", "Por busqueda propia" }));
        getContentPane().add(conocidoF, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 220, -1, -1));

        buttonGroup1.add(alta);
        alta.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        alta.setText("ALTA");
        getContentPane().add(alta, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 290, -1, -1));

        buttonGroup1.add(baja);
        baja.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        baja.setSelected(true);
        baja.setText("BAJA");
        baja.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bajaActionPerformed(evt);
            }
        });
        getContentPane().add(baja, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, -1, -1));

        reservar.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        reservar.setForeground(new java.awt.Color(255, 255, 255));
        reservar.setText("RESERVAR");
        reservar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                reservarActionPerformed(evt);
            }
        });
        getContentPane().add(reservar, new org.netbeans.lib.awtextra.AbsoluteConstraints(180, 340, 150, 40));

        jSeparator2.setBackground(new java.awt.Color(0, 0, 255));
        jSeparator2.setForeground(new java.awt.Color(0, 0, 255));
        jSeparator2.setFont(new java.awt.Font("Segoe UI", 0, 24)); // NOI18N
        getContentPane().add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 110, 370, 40));
        getContentPane().add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 180, 370, 10));
        getContentPane().add(jSeparator4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 250, 370, 10));
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        getContentPane().add(fondoAPP, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 540, 400));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void nombreFActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_nombreFActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_nombreFActionPerformed

    private void reservarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_reservarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_reservarActionPerformed

    private void bajaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bajaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_bajaActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Reservar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Reservar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JRadioButton alta;
    private javax.swing.JRadioButton baja;
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JLabel claseL;
    private javax.swing.JComboBox<String> conocidoF;
    private javax.swing.JLabel conocidoL;
    private javax.swing.JTextField dniF;
    private javax.swing.JLabel dniL;
    private javax.swing.JLabel fondoAPP;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JTextField nombreF;
    private javax.swing.JLabel nombreL;
    private javax.swing.JButton reservar;
    private javax.swing.JLabel txtReservarHab;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        /**
         * If you press this button you can go back to the previous frame.
         */
        if(e.getSource()==volver){
            try {
                framePrin = new Pantalla_Principal();
                framePrin.setVisible(true);
                this.setVisible(false);
            } catch (SQLException ex) {
                Logger.getLogger(Reservar.class.getName()).log(Level.SEVERE, null, ex);
            }
            
            /**
             * If you press this button you will reserve a room.
             */
        }else if(e.getSource()==reservar){
            try {
                
                if(compDni(dniF.getText())){
                    bd = new AccesoBD("hotel_interfaces");
                
                if(alta.isSelected()){
                    bd.insertarReserva(nombreF.getText().toString(), dniF.getText().toString(), conocidoF.getSelectedItem().toString(), alta.getText().toString(), Integer.parseInt(idHotel.getText().toString()));
                    nombreF.setText("");
                    dniF.setText("");
                    JOptionPane.showMessageDialog(this, "La habitacion se ha reservado.");
                }else{
                    bd.insertarReserva(nombreF.getText().toString(), dniF.getText().toString(), conocidoF.getSelectedItem().toString(), baja.getText().toString(), Integer.parseInt(idHotel.getText().toString()));
                    nombreF.setText("");
                    dniF.setText("");
                    JOptionPane.showMessageDialog(this, "La habitacion se ha reservado.");
                }
                }else{
                    JOptionPane.showMessageDialog(this, "Introduce un dni correcto.", "Error", JOptionPane.ERROR_MESSAGE);

                }
                
                
                
            } catch (SQLException ex) {
                Logger.getLogger(Reservar.class.getName()).log(Level.SEVERE, null, ex);
            }
        }
    }
}
