/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package pantallas;

import bd.ManejadorDB;
import java.awt.Color;
import java.awt.event.ActionEvent;
import java.awt.event.ActionListener;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.BorderFactory;
import javax.swing.ImageIcon;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;

/**
 * In this jframe the user will be able to see the reservations he has made 
 * using his ID to search for them.
 * The reservations will be represented in a JTable and will contain all 
 * the information about the reservation.
 * @author Admin
 */
public class Ver_Reservas extends javax.swing.JFrame implements ActionListener{

    /**
     * Creates new form Ver_Reservas
     */
    DefaultTableModel modelo;
    public Ver_Reservas() {
        initComponents();
        
        /**
         * This is a model for table, contains the columns for her.
         */
        modelo = new DefaultTableModel();
        modelo.addColumn("ID:");
        modelo.addColumn("NOMBRE:");
        modelo.addColumn("DNI:");
        modelo.addColumn("CLASE:");
        modelo.addColumn("HOTEL:");
        
        ImageIcon fondo1 = new ImageIcon("src/fondoAPP.png");
        fondo.setIcon(fondo1);
        
        this.tabla.setModel(modelo); //Add the moder in the table
        
        
        /**
         * Set background for a table ans scrollpane
         */
        tabla.setOpaque(false);
        ((DefaultTableCellRenderer)tabla.getDefaultRenderer(Object.class)).setOpaque(false);
        
        ImageIcon vol = new ImageIcon("src/volver.png");
        volver.setIcon(vol);
        volver.setBorder(BorderFactory.createEmptyBorder());
        volver.setBackground(new Color(0,0,0,0));
        
        jScrollPane1.setOpaque(false);
        jScrollPane1.getViewport().setOpaque(false);
        
        volver.addActionListener(this);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        tabla = new javax.swing.JTable();
        dniF = new javax.swing.JTextField();
        textoDNI = new javax.swing.JLabel();
        txtMisReservas = new javax.swing.JLabel();
        buscar = new javax.swing.JButton();
        volver = new javax.swing.JButton();
        fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        tabla.setFont(new java.awt.Font("Times New Roman", 1, 14)); // NOI18N
        tabla.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "ID:", "NOMBRE:", "DNI:", "CLASE:", "HOTEL:"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tabla);

        getContentPane().add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 140, 440, 190));
        getContentPane().add(dniF, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 80, 80, -1));

        textoDNI.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        textoDNI.setText("Introduce tu DNI:");
        getContentPane().add(textoDNI, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 80, -1, -1));

        txtMisReservas.setFont(new java.awt.Font("Serif", 1, 24)); // NOI18N
        txtMisReservas.setText("MIS RESERVAS");
        getContentPane().add(txtMisReservas, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 10, -1, -1));

        buscar.setBackground(new java.awt.Color(0, 0, 0));
        buscar.setFont(new java.awt.Font("Times New Roman", 1, 12)); // NOI18N
        buscar.setForeground(new java.awt.Color(255, 255, 255));
        buscar.setText("BUSCAR");
        buscar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                buscarActionPerformed(evt);
            }
        });
        getContentPane().add(buscar, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 80, -1, -1));
        getContentPane().add(volver, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 40, 40));
        getContentPane().add(fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 480, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    /**
     * If you press the search button, the client's reservations will be 
     * searched in the database.
     * If the client is not found in the database or the ID is wrong, a warning 
     * message will be issued.
     * The reservations will be added to the table.
     * @param evt 
     */
    private void buscarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_buscarActionPerformed
        ManejadorDB db;
        try {
            db = new ManejadorDB("hotel_interfaces");
            ResultSet rr = db.consulta("SELECT * FROM reservas WHERE dni = '"+dniF.getText().toString()+"'");
            
            
            while(rr.next()){
                
                String [] info = new String[5];
                info[0]=rr.getInt("id")+"";
                info[1]=rr.getString("nombre");
                info[2]=rr.getString("dni");
                info[3]=rr.getString("clase");
                
                ResultSet rr2;
                rr2=db.consulta2("SELECT * FROM hoteles WHERE id = '"+rr.getString("id_hotel")+"'");
                while(rr2.next()){
                info[4]=rr2.getString("nombre");
                }
                rr2.close();
                modelo.addRow(info);
            }
            
            db.cerrarTodo();
        } catch (SQLException ex) {
            Logger.getLogger(Ver_Reservas.class.getName()).log(Level.SEVERE, null, ex);
        }
        
        if(tabla.getRowCount()==0){
            JOptionPane.showMessageDialog(this, "No se han encontrado reservas.");
        }
        
    }//GEN-LAST:event_buscarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Ver_Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Ver_Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Ver_Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Ver_Reservas.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Ver_Reservas().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton buscar;
    private javax.swing.JTextField dniF;
    private javax.swing.JLabel fondo;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tabla;
    private javax.swing.JLabel textoDNI;
    private javax.swing.JLabel txtMisReservas;
    private javax.swing.JButton volver;
    // End of variables declaration//GEN-END:variables

    @Override
    public void actionPerformed(ActionEvent e) {
        /**
         * If you press this button you can go back to the previous frame.
         */
        if(e.getSource()==volver){
            Pantalla_Principal p = null;
            try {
                p = new Pantalla_Principal();
            } catch (SQLException ex) {
                Logger.getLogger(Pantalla_Descriptiva.class.getName()).log(Level.SEVERE, null, ex);
            }
            this.setVisible(false);
            p.setVisible(true);
        }
    }
}
